# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BDOT10k_GML_SHP_Loader
                                 A QGIS plugin
 Importuje BDOT10k w formacie GML albo SHP
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-05-04
        copyright            : (C) 2020 by Marcin Lebiecki / Główny Urząd Geodezji i Kartografii
        email                : marcin.lebiecki@gugik.gov.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BDOT10k_GML_SHP_Loader class from file BDOT10k_GML_SHP_Loader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .BDOT10k_GML_SHP_Loader import BDOT10k_GML_SHP_Loader
    return BDOT10k_GML_SHP_Loader(iface)
